// <auto-generated />
using System;
using ConferenceRoomBooking.Dal.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceRoomBooking.Dal.Db.Migrations
{
    [DbContext(typeof(ConferenceRoomBookingDbContext))]
    [Migration("20241025103652_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingEntityServiceEntity", b =>
                {
                    b.Property<Guid>("BookingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("BookingEntityServiceEntity");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Dal.Db.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConferenceRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HourAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceRoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Dal.Db.Entities.ConferenceRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f16c6f1e-4fe5-45ee-843d-bb0385f872be"),
                            Capacity = 50,
                            DateCreated = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1119),
                            LastModifiedDate = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1165),
                            Name = "A",
                            PricePerHour = 2000m
                        },
                        new
                        {
                            Id = new Guid("62fe6ee7-0497-46d6-a51d-96fdf673fc48"),
                            Capacity = 100,
                            DateCreated = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1169),
                            LastModifiedDate = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1170),
                            Name = "B",
                            PricePerHour = 3500m
                        },
                        new
                        {
                            Id = new Guid("077eca9b-7b0c-4edb-86ca-12dab06958b5"),
                            Capacity = 30,
                            DateCreated = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1173),
                            LastModifiedDate = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1174),
                            Name = "C",
                            PricePerHour = 1500m
                        });
                });

            modelBuilder.Entity("ConferenceRoomBooking.Dal.Db.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab15467d-7b56-4c3d-a3ff-8078ff1b65e9"),
                            DateCreated = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1858),
                            LastModifiedDate = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1862),
                            Name = "Проєктор",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("09d4c617-121a-4f26-b16b-35b0a7067e7e"),
                            DateCreated = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1865),
                            LastModifiedDate = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1866),
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("b198648c-2307-4223-8b4d-7758f88181c4"),
                            DateCreated = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1946),
                            LastModifiedDate = new DateTime(2024, 10, 25, 13, 36, 51, 898, DateTimeKind.Local).AddTicks(1948),
                            Name = "Звук",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("ConferenceRoomEntityServiceEntity", b =>
                {
                    b.Property<Guid>("ConferenceRoomsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConferenceRoomsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ConferenceRoomEntityServiceEntity");
                });

            modelBuilder.Entity("BookingEntityServiceEntity", b =>
                {
                    b.HasOne("ConferenceRoomBooking.Dal.Db.Entities.BookingEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomBooking.Dal.Db.Entities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceRoomBooking.Dal.Db.Entities.BookingEntity", b =>
                {
                    b.HasOne("ConferenceRoomBooking.Dal.Db.Entities.ConferenceRoomEntity", "ConferenceRoom")
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");
                });

            modelBuilder.Entity("ConferenceRoomEntityServiceEntity", b =>
                {
                    b.HasOne("ConferenceRoomBooking.Dal.Db.Entities.ConferenceRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("ConferenceRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomBooking.Dal.Db.Entities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
